### ISSUE TITLE
JSON dependency on Ruby >2.4

### ISSUE THREAD

**Issue by palumbamboo** [contentful/contentful-management.rb#151]
Is there a way to eliminate forced dependency with json 1.8 or at least one way to get compatibility with Ruby 2.4?

**Comment by dlitvakb** [comment]
Hey @CavalloCrop,

The dependency version fix could be dropped, but 1.8.x is compatible with Ruby 2.4.x, Ruby 2.5.x and Ruby@HEAD. Therefore you shouldn't be seeing any issues.

I'll add this to my backlog as we're soon to start deprecating support for 1.x releases of Ruby and this update is one of the steps into doing that.

Cheers

**Comment by kamui** [comment]
@dlitvakb Somewhat related, but since the `json` is now up to version 2.x I was wondering if could bump the json version dependency to `>= 1.8`?

I have another gem that required json 2.x and this is causing a conflict. Because json 2.x seems to add better compatibility with ruby 2.4, 2.6 and `RFC 7159` compliance, it seems like a good idea support it?

**Comment by bcapdevilac** [comment]
Same issue here - is there any plan to merge @kamui PR https://github.com/contentful/contentful-management.rb/pull/196 soon?

**Comment by dlitvakb** [comment]
Merged, will release soon.
