### ISSUE TITLE
Pagination for all entries returns duplicate entries

### ISSUE THREAD

**Issue by mxlje** [contentful/contentful-management.rb#175]
Objective: make an automated change to a subset of fields of every entry of a specific content type, save, and publish the entry.

From reading the documentation, I have to create a client, find an environment, and then call `env.entries.all`, which returns a paginated response. Then loop over the items in the page and call `next_page` to walk through all the pages.

I wrote this script:

```ruby
entries = env.entries.all(content_type: 'post')

i = 0
while entries.count > 0
  entries.each do |post|
    i += 1

    old_title = post.title
    new_title = some_transformation_function(old_title)

    # update post title
    post.title = new_title
    
    # save & publish entry
    post.save
    post.publish

    puts "#{i},#{post.id},#{old_title},#{new_title}"
  end

  entries = entries.next_page
end
```

I ran it without the actual updating and saving to see if the pagination logic worked, and it seemed to be ok. It ran exactly as many iterations as I have entries of that type, which I considered working (329 in my case).

I ran the script a 2nd time (with the transformations this time) and it, too, ran for 329 iterations before exiting. After examining the log more closely, though, I noticed that there were 64 duplicate entries in my log output. I then checked CF itself and indeed, not every one of the entries was updated by the script.

It started iterating and changing some entries, and then, later on, iterated over some of the entries _again_. Example log output (updated for readability):

```
…
86,  id-foo-bar, old title, new title
…
184, id-foo-bar, new title, new title
…
```

You can see that the 2nd time around the entry already has the new title as it was saved previously.

Here’s the main question: What’s going on?

- Am i paginating through the results incorrectly?
- Why am I getting entries again, after they were already part of a previous page?
- If not like this, how am I supposed to run such a workflow?

Some wild speculation at the end: updating entries in such a loop changes their `updated_at` field (of course) and then the internal order of entries through which CF paginates changes and pushes entries to the next page, therefore they’re picked up again.

Thank you for any pointers.

**Comment by dlitvakb** [comment]
Hey @mxlje,

This is happening because unless using a strict order parameter, there's no guarantees that the returned content will be the proper content you're expecting. This is documented here: https://www.contentful.com/developers/docs/references/content-management-api/#/introduction/collection-resources-and-pagination

Also, I'd advise doing pagination a bit differently, something similar to what is done for the Middleman integration for example: https://github.com/contentful/contentful_middleman/blob/master/lib/contentful_middleman/instance.rb#L47-L61 with the minor caveat that you need to change the client from the Delivery API to the Management API, but otherwise everything is the same.

Cheers

**Comment by mxlje** [comment]
Thank you for your reply. That looks like it answers my question, I’ll check out the example pagination code you sent, too.
