### ISSUE TITLE
Checking if entry/asset is "changed"

### ISSUE THREAD

**Issue by andreyrd** [contentful/contentful-management.rb#178]
https://github.com/contentful/contentful-management.rb#entries 

Currently, looks like we can check if a resource has ever been published, using `my_entry.published?`.
But that returns true even if the entry has been changed.

1. Is the proper approach to check if `my_entry["sys"]["updatedAt"] > my_entry["sys"]["publishedAt"]`?
2. Is it worth adding a `changed?` method?

**Comment by dlitvakb** [comment]
Hey @andreyrd,

For 1, that's the correct approach.

For 2, `#changed?` may be a bad name, maybe `#pending_changes?` is better, and yes, can be added. But that would also mean I would need to implement `#dirty?` in order to differentiate changed values in the object itself vs changed values in the API.

I'll be looking into adding this very soon, as I'm going to be working this week on adding a few new features to this SDK.

Cheers
