### ISSUE TITLE
Inconsistent 400/409 errors

### ISSUE THREAD

**Issue by paulstraw** [contentful/contentful-management.rb#244]
Hi there! My company has set up the contentful-management gem in our application (combined with contentful-migrations). This lets us store migrations in the codebase and automatically deploy them alongside other code changes. Overall, the system works fairly well.

Unfortunately, we get frequent 400/409 errors from contentful-management when migrations are run as part of the CD pipeline. Initially, I thought this might be the same problem as described in #158, but now I'm not so sure. Earlier today, this migration failed twice before succeeding (once 400, once 409):

``` ruby
feature_bullet_type = space.content_types.find('featureBullet')

# Update editor interface for "description" control.
editor_interface = feature_bullet_type.editor_interface.default
description_control = editor_interface.controls.detect do |c|
  c['fieldId'] == 'description'
end
description_control['widgetId'] = 'multipleLine'

editor_interface.save
```

Specifically, these are the errors that were raised when trying to run that migration:

**400**

```
Contentful::Management::BadRequest: HTTP status code: 400 Bad Request
Message: You should provide a content type in X-Contentful-Content-Type request header.
```

**409**

```
Contentful::Management::Conflict: HTTP status code: 409 Conflict
Message: Version mismatch error. The version you specified was incorrect. This may be due to someone else editing the content.
```

The reason this migration stood out to me is that unlike in #158, no new content type is being published. All that's happening is an editor interface update, so I'm not even clear what we would be able to delay in this case. That said, we've also seen this happen in migrations that _do_ look more like #158.

This happens for lots of migrations without any apparent pattern. We've had some difficulty troubleshooting it so far; only one of our engineers has been able to reproduce this locally, and not consistently. It seems to have some correlation with being on an extremely fast WAN connection.

**Comment by seand7565** [comment]
I think I have a read on why this happens.

In `execute_request` in [the client](https://github.com/contentful/contentful-management.rb/blob/2894d05e709869665de5292a7853c627d830678c/lib/contentful/management/client.rb#L377), we enter into a transaction block, perform the request, clear the headers and if there are any errors (& errors are turned on), we raise them.

However, this causes issues when the RateLimitError is raised. When that's raised, the request is retried; But because `clear_headers` has already run by this point, the request is run without those headers. I believe this is causing both of the above issues. At least, I'm able to replicate the `409` by triggering a rate limit error. The `400` error is also header related, so I'm assuming it's the same issue.

**Comment by rubydog** [comment]
PR merged: https://github.com/contentful/contentful-management.rb/pull/245
